const korea = { code: 'KR', name: 'South Korea (대한민국)', dial: '+82' };

const rest = [
    { code: 'AF', name: 'Afghanistan (아프가니스탄)', dial: '+93' },
    { code: 'DZ', name: 'Algeria (알제리)', dial: '+213' },
    { code: 'AO', name: 'Angola (앙골라)', dial: '+244' },
    { code: 'AR', name: 'Argentina (아르헨티나)', dial: '+54' },
    { code: 'AU', name: 'Australia (호주)', dial: '+61' },
    { code: 'AT', name: 'Austria (오스트리아)', dial: '+43' },
    { code: 'BD', name: 'Bangladesh (방글라데시)', dial: '+880' },
    { code: 'BY', name: 'Belarus (벨라루스)', dial: '+375' },
    { code: 'BE', name: 'Belgium (벨기에)', dial: '+32' },
    { code: 'BO', name: 'Bolivia (볼리비아)', dial: '+591' },
    { code: 'BR', name: 'Brazil (브라질)', dial: '+55' },
    { code: 'BN', name: 'Brunei (브루나이)', dial: '+673' },
    { code: 'BG', name: 'Bulgaria (불가리아)', dial: '+359' },
    { code: 'KH', name: 'Cambodia (캄보디아)', dial: '+855' },
    { code: 'CA', name: 'Canada (캐나다)', dial: '+1' },
    { code: 'CL', name: 'Chile (칠레)', dial: '+56' },
    { code: 'CN', name: 'China (중국)', dial: '+86' },
    { code: 'CO', name: 'Colombia (콜롬비아)', dial: '+57' },
    { code: 'CR', name: 'Costa Rica (코스타리카)', dial: '+506' },
    { code: 'HR', name: 'Croatia (크로아티아)', dial: '+385' },
    { code: 'CU', name: 'Cuba (쿠바)', dial: '+53' },
    { code: 'CZ', name: 'Czech Republic (체코)', dial: '+420' },
    { code: 'DK', name: 'Denmark (덴마크)', dial: '+45' },
    { code: 'DO', name: 'Dominican Republic (도미니카 공화국)', dial: '+1' },
    { code: 'EC', name: 'Ecuador (에콰도르)', dial: '+593' },
    { code: 'EG', name: 'Egypt (이집트)', dial: '+20' },
    { code: 'EE', name: 'Estonia (에스토니아)', dial: '+372' },
    { code: 'FI', name: 'Finland (핀란드)', dial: '+358' },
    { code: 'FR', name: 'France (프랑스)', dial: '+33' },
    { code: 'DE', name: 'Germany (독일)', dial: '+49' },
    { code: 'GH', name: 'Ghana (가나)', dial: '+233' },
    { code: 'GR', name: 'Greece (그리스)', dial: '+30' },
    { code: 'GT', name: 'Guatemala (과테말라)', dial: '+502' },
    { code: 'HN', name: 'Honduras (온두라스)', dial: '+504' },
    { code: 'HK', name: 'Hong Kong (홍콩)', dial: '+852' },
    { code: 'HU', name: 'Hungary (헝가리)', dial: '+36' },
    { code: 'IS', name: 'Iceland (아이슬란드)', dial: '+354' },
    { code: 'IN', name: 'India (인도)', dial: '+91' },
    { code: 'ID', name: 'Indonesia (인도네시아)', dial: '+62' },
    { code: 'IR', name: 'Iran (이란)', dial: '+98' },
    { code: 'IE', name: 'Ireland (아일랜드)', dial: '+353' },
    { code: 'IL', name: 'Israel (이스라엘)', dial: '+972' },
    { code: 'IT', name: 'Italy (이탈리아)', dial: '+39' },
    { code: 'JM', name: 'Jamaica (자메이카)', dial: '+1' },
    { code: 'JP', name: 'Japan (일본)', dial: '+81' },
    { code: 'KZ', name: 'Kazakhstan (카자흐스탄)', dial: '+7' },
    { code: 'KE', name: 'Kenya (케냐)', dial: '+254' },
    { code: 'KW', name: 'Kuwait (쿠웨이트)', dial: '+965' },
    { code: 'LA', name: 'Laos (라오스)', dial: '+856' },
    { code: 'LV', name: 'Latvia (라트비아)', dial: '+371' },
    { code: 'LT', name: 'Lithuania (리투아니아)', dial: '+370' },
    { code: 'MY', name: 'Malaysia (말레이시아)', dial: '+60' },
    { code: 'MX', name: 'Mexico (멕시코)', dial: '+52' },
    { code: 'MN', name: 'Mongolia (몽골)', dial: '+976' },
    { code: 'MA', name: 'Morocco (모로코)', dial: '+212' },
    { code: 'MM', name: 'Myanmar (미얀마)', dial: '+95' },
    { code: 'NP', name: 'Nepal (네팔)', dial: '+977' },
    { code: 'NL', name: 'Netherlands (네덜란드)', dial: '+31' },
    { code: 'NZ', name: 'New Zealand (뉴질랜드)', dial: '+64' },
    { code: 'NG', name: 'Nigeria (나이지리아)', dial: '+234' },
    { code: 'NO', name: 'Norway (노르웨이)', dial: '+47' },
    { code: 'OM', name: 'Oman (오만)', dial: '+968' },
    { code: 'PK', name: 'Pakistan (파키스탄)', dial: '+92' },
    { code: 'PA', name: 'Panama (파나마)', dial: '+507' },
    { code: 'PY', name: 'Paraguay (파라과이)', dial: '+595' },
    { code: 'PE', name: 'Peru (페루)', dial: '+51' },
    { code: 'PH', name: 'Philippines (필리핀)', dial: '+63' },
    { code: 'PL', name: 'Poland (폴란드)', dial: '+48' },
    { code: 'PT', name: 'Portugal (포르투갈)', dial: '+351' },
    { code: 'QA', name: 'Qatar (카타르)', dial: '+974' },
    { code: 'RO', name: 'Romania (루마니아)', dial: '+40' },
    { code: 'RU', name: 'Russia (러시아)', dial: '+7' },
    { code: 'SA', name: 'Saudi Arabia (사우디아라비아)', dial: '+966' },
    { code: 'RS', name: 'Serbia (세르비아)', dial: '+381' },
    { code: 'SG', name: 'Singapore (싱가포르)', dial: '+65' },
    { code: 'SK', name: 'Slovakia (슬로바키아)', dial: '+421' },
    { code: 'SI', name: 'Slovenia (슬로베니아)', dial: '+386' },
    { code: 'ZA', name: 'South Africa (남아프리카 공화국)', dial: '+27' },
    { code: 'ES', name: 'Spain (스페인)', dial: '+34' },
    { code: 'LK', name: 'Sri Lanka (스리랑카)', dial: '+94' },
    { code: 'SE', name: 'Sweden (스웨덴)', dial: '+46' },
    { code: 'CH', name: 'Switzerland (스위스)', dial: '+41' },
    { code: 'TW', name: 'Taiwan (대만)', dial: '+886' },
    { code: 'TH', name: 'Thailand (태국)', dial: '+66' },
    { code: 'TN', name: 'Tunisia (튀니지)', dial: '+216' },
    { code: 'TR', name: 'Turkey (튀르키예)', dial: '+90' },
    { code: 'UA', name: 'Ukraine (우크라이나)', dial: '+380' },
    { code: 'AE', name: 'United Arab Emirates (아랍에미리트)', dial: '+971' },
    { code: 'GB', name: 'United Kingdom (영국)', dial: '+44' },
    { code: 'US', name: 'United States (미국)', dial: '+1' },
    { code: 'UG', name: 'Uganda (우간다)', dial: '+256' },
    { code: 'UY', name: 'Uruguay (우루과이)', dial: '+598' },
    { code: 'UZ', name: 'Uzbekistan (우즈베키스탄)', dial: '+998' },
    { code: 'VE', name: 'Venezuela (베네수엘라)', dial: '+58' },
    { code: 'VN', name: 'Vietnam (베트남)', dial: '+84' },
    { code: 'ZM', name: 'Zambia (잠비아)', dial: '+260' },
    { code: 'ZW', name: 'Zimbabwe (짐바브웨)', dial: '+263' },
    { code: 'OTHER', name: 'Other (기타)', dial: '' },
];

export const COUNTRIES = [korea, ...rest];
