export const COUNTRIES = [
    { code: 'KR', name: 'South Korea (대한민국)' },
    { code: 'US', name: 'United States (미국)' },
    { code: 'CN', name: 'China (중국)' },
    { code: 'JP', name: 'Japan (일본)' },
    { code: 'TW', name: 'Taiwan (대만)' },
    { code: 'HK', name: 'Hong Kong (홍콩)' },
    { code: 'VN', name: 'Vietnam (베트남)' },
    { code: 'TH', name: 'Thailand (태국)' },
    { code: 'PH', name: 'Philippines (필리핀)' },
    { code: 'MY', name: 'Malaysia (말레이시아)' },
    { code: 'SG', name: 'Singapore (싱가포르)' },
    { code: 'ID', name: 'Indonesia (인도네시아)' },
    { code: 'IN', name: 'India (인도)' },
    { code: 'AU', name: 'Australia (호주)' },
    { code: 'NZ', name: 'New Zealand (뉴질랜드)' },
    { code: 'GB', name: 'United Kingdom (영국)' },
    { code: 'FR', name: 'France (프랑스)' },
    { code: 'DE', name: 'Germany (독일)' },
    { code: 'IT', name: 'Italy (이탈리아)' },
    { code: 'ES', name: 'Spain (스페인)' },
    { code: 'NL', name: 'Netherlands (네덜란드)' },
    { code: 'CH', name: 'Switzerland (스위스)' },
    { code: 'SE', name: 'Sweden (스웨덴)' },
    { code: 'DK', name: 'Denmark (덴마크)' },
    { code: 'NO', name: 'Norway (노르웨이)' },
    { code: 'FI', name: 'Finland (핀란드)' },
    { code: 'AT', name: 'Austria (오스트리아)' },
    { code: 'BE', name: 'Belgium (벨기에)' },
    { code: 'RU', name: 'Russia (러시아)' },
    { code: 'CA', name: 'Canada (캐나다)' },
    { code: 'MX', name: 'Mexico (멕시코)' },
    { code: 'BR', name: 'Brazil (브라질)' },
    { code: 'AR', name: 'Argentina (아르헨티나)' },
    { code: 'CL', name: 'Chile (칠레)' },
    { code: 'CO', name: 'Colombia (콜롬비아)' },
    { code: 'PE', name: 'Peru (페루)' },
    { code: 'ZA', name: 'South Africa (남아프리카 공화국)' },
    { code: 'EG', name: 'Egypt (이집트)' },
    { code: 'MA', name: 'Morocco (모로코)' },
    { code: 'KE', name: 'Kenya (케냐)' },
    { code: 'NG', name: 'Nigeria (나이지리아)' },
    { code: 'SA', name: 'Saudi Arabia (사우디아라비아)' },
    { code: 'AE', name: 'United Arab Emirates (아랍에미리트)' },
    { code: 'TR', name: 'Turkey (튀르키예)' },
    { code: 'IR', name: 'Iran (이란)' },
    { code: 'IL', name: 'Israel (이스라엘)' },
    { code: 'PK', name: 'Pakistan (파키스탄)' },
    { code: 'BD', name: 'Bangladesh (방글라데시)' },
    { code: 'LK', name: 'Sri Lanka (스리랑카)' },
    { code: 'KH', name: 'Cambodia (캄보디아)' },
    { code: 'MM', name: 'Myanmar (미얀마)' },
    { code: 'LA', name: 'Laos (라오스)' },
    { code: 'BN', name: 'Brunei (브루나이)' },
    { code: 'MN', name: 'Mongolia (몽골)' },
    { code: 'KZ', name: 'Kazakhstan (카자흐스탄)' },
    { code: 'UZ', name: 'Uzbekistan (우즈베키스탄)' },
    { code: 'PT', name: 'Portugal (포르투갈)' },
    { code: 'GR', name: 'Greece (그리스)' },
    { code: 'PL', name: 'Poland (폴란드)' },
    { code: 'CZ', name: 'Czech Republic (체코)' },
    { code: 'HU', name: 'Hungary (헝가리)' },
    { code: 'RO', name: 'Romania (루마니아)' },
    { code: 'BG', name: 'Bulgaria (불가리아)' },
    { code: 'HR', name: 'Croatia (크로아티아)' },
    { code: 'RS', name: 'Serbia (세르비아)' },
    { code: 'SK', name: 'Slovakia (슬로바키아)' },
    { code: 'SI', name: 'Slovenia (슬로베니아)' },
    { code: 'EE', name: 'Estonia (에스토니아)' },
    { code: 'LV', name: 'Latvia (라트비아)' },
    { code: 'LT', name: 'Lithuania (리투아니아)' },
    { code: 'IE', name: 'Ireland (아일랜드)' },
    { code: 'IS', name: 'Iceland (아이슬란드)' },
    { code: 'UA', name: 'Ukraine (우크라이나)' },
    { code: 'BO', name: 'Bolivia (볼리비아)' },
    { code: 'EC', name: 'Ecuador (에콰도르)' },
    { code: 'PY', name: 'Paraguay (파라과이)' },
    { code: 'UY', name: 'Uruguay (우루과이)' },
    { code: 'VE', name: 'Venezuela (베네수엘라)' },
    { code: 'CR', name: 'Costa Rica (코스타리카)' },
    { code: 'CU', name: 'Cuba (쿠바)' },
    { code: 'DO', name: 'Dominican Republic (도미니카 공화국)' },
    { code: 'GT', name: 'Guatemala (과테말라)' },
    { code: 'HN', name: 'Honduras (온두라스)' },
    { code: 'JM', name: 'Jamaica (자메이카)' },
    { code: 'PA', name: 'Panama (파나마)' },
    { code: 'AF', name: 'Afghanistan (아프가니스탄)' },
    { code: 'NP', name: 'Nepal (네팔)' },
    { code: 'QA', name: 'Qatar (카타르)' },
    { code: 'KW', name: 'Kuwait (쿠웨이트)' },
    { code: 'OM', name: 'Oman (오만)' },
    { code: 'BY', name: 'Belarus (벨라루스)' },
    { code: 'DZ', name: 'Algeria (알제리)' },
    { code: 'AO', name: 'Angola (앙골라)' },
    { code: 'GH', name: 'Ghana (가나)' },
    { code: 'TN', name: 'Tunisia (튀니지)' },
    { code: 'UG', name: 'Uganda (우간다)' },
    { code: 'ZM', name: 'Zambia (잠비아)' },
    { code: 'ZW', name: 'Zimbabwe (짐바브웨)' },
    { code: 'OTHER', name: 'Other (기타)' },
];
